trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: 
    displayName: 'Deploy to Azure Web App'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'nextjs-build'
        path: '$(Pipeline.Workspace)/nextjs-build'

    - script: |
        mv $(Pipeline.Workspace)/nextjs-build/* /home/site/wwwroot/
      displayName: 'Move build artifacts to wwwroot'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'your-azure-connection'
        appType: 'webAppLinux'
        appName: 'amalcicd1'
        package: '$(Pipeline.Workspace)/nextjs-build'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'your-azure-connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az webapp config set --name amalcicd1 --resource-group Demo --startup-file 'npm start'
